### ISSUE TITLE
where is the noise component in the matlab code？

### ISSUE THREAD

**Issue by xxxkxin** [jkjaer/fastF0Nls#1]
I can't find the noise component of the generated test signal. There is only a linear parameter “alpha” which is set randomly in test.m line24，line74，line110 . But it dosen't seem like a noise component. So how can i change the SNR and the noise type of test signal？

**Comment by jkjaer** [comment]
Hi,

There is no noise added since the purpose of the test is to make sure that the correct pitch is estimated when all modelling assumptions are fullfilled and no noise is added.

If you want to add noise to a signal at a particular SNR, please see, e.g., the awgn function in MATLAB. Please also look at the examples in the examples folder.

**Comment by 22898** [comment]
你好，我想问下，你这是全部的代码吗，我是个初学者，想你给我点帮助，建议
