### ISSUE TITLE
some questions about cpp codes

### ISSUE THREAD

**Issue by xxxkxin** [jkjaer/fastF0Nls#2]

**Comment by xxxkxin** [comment]
1. parameter "nPitches" decreases to zero before the iteration ends when this function runs. "single_pitch::single_pitch(int L, int F, int N, FTYPE * pB)" at "int nPitches = maxFftIndex - minFftIndex + 1;" 
2. The program will report an error when the lower bound is greater than 0.1. So we wonder is there any relationship between "pitchBounds" and "maxModelOrder" or other parameters?
3. We compared the cpp code and matlab code, but didn't find corresponding "omega_0h"(in single_pitch.cpp line25) in matlab code. And the number of elements of "Gamma1", "Gamma2" is unequal.

**Comment by jkjaer** [comment]
1) How did you specify the pitch bounds (the fourth input parameter)? It is a 2D vector specifying the search range for the pitch? The first element must be smaller than the last element. See line 14 and 23 of https://github.com/jkjaer/fastF0Nls/blob/master/cpp/timing/profile.cpp for an example of how the pitch bounds can be specified.
2) The frequency unit used is cycles/sample. To satisfy the Nyquist sampling theorem, the pitch must, therefore, be smaller than 0.5 cycles/sample. If you specify a lower bound of 0.1 cycles/samples and a maximum model order of 10, say, you are violating the Nyquist sampling theorem for all candidate model orders larger than or equal to 5. If think this might be related to the error, you see.
3) The MATLAB code has been updated since the initial upload whereas the C++ code has not been updated. Moreover, the C++ code and the MATLAB code have been written by two different persons so the notation is not completely consistent. When the code was initially released, the C++ code and the MATLAB code produced the exact same results. You can go through the commit history to see what has been changed in the MATLAB code. As far as I recall, only minor modifications have been made.
